export const ACTION_TYPE = {
	LOGOUT: 'LOGOUT',
	SET_CATEGORY: 'SET_CATEGORY',
	SET_PAGE: 'SET_PAGE',
	SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
	SET_SHOULD_SEARCH: 'SET_SHOULD_SEARCH',
	SET_USER: 'SET_USER',
};
