export const ACTION_TYPE = {
	ADD_TO_CART: 'ADD_TO_CART',
	EDIT_CART: 'EDIT_CART',
	LOGOUT: 'LOGOUT',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	RESET_SEARCH_FILTERS: 'RESET_SEARCH_FILTERS',
	SET_CART: 'SET_CART',
	SET_CATEGORY: 'SET_CATEGORY',
	SET_PAGE: 'SET_PAGE',
	SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
	SET_SHOULD_SEARCH: 'SET_SHOULD_SEARCH',
	SET_SORTING: 'SET_SORTING',
	SET_USER: 'SET_USER',
};
